version: '3.8'

services:
  # FastAPI Application
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DEBUG=True
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://platformdavid:${POSTGRES_PASSWORD:-platformdavid}@db:5432/platformdavid_db}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-jwt-secret-key-change-in-production}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=platformdavid_db
      - POSTGRES_USER=platformdavid
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-platformdavid}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Celery Worker
  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://platformdavid:${POSTGRES_PASSWORD:-platformdavid}@db:5432/platformdavid_db}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
